####
POST http://localhost:9000/api/auth/register
Content-Type: application/json

{
    "name":"ihihi",
    "email":"uxup@gmail.com",
    "password":"oke123"
}

###
POST http://localhost:9000/api/auth/login
Content-Type: application/json

{
    "email":"sahey@gmail.com",
    "password":"oke123"
}

###
POST http://localhost:9000/api/auth/login
Content-Type: application/json

{
    "email":"admin3@gmail.com",
    "password":"oke123"
}

####
POST http://localhost:9000/api/auth/login
Content-Type: application/json

{
    "email":"superadmin@gmail.com",
    "password":"oke123"
}
###
GET http://localhost:9000/api/auth/user


####cars
###
GET http://localhost:9000/api/cars/show
###
GET http://localhost:9000/api/cars/show/2

####
GET http://localhost:9000/api/cars/show/type/medium